/*
Initial JSX Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useStore, GAME_STATES } from "./Store";

export default function Tamagotchi(props) {
	const { nodes, materials } = useGLTF("/tamagotchi.glb");

	const tamagotchiRef = useRef();
	const leftButtonRef = useRef();
	const middleButtonRef = useRef();
	const rightButtonRef = useRef();

	const { currentState, scoreTotal, foodScores, setState, feedFood } =
		useStore();
	useEffect(() => {
		console.log(`Current State: ${currentState}`);
		console.log(`CurrentScore: ${scoreTotal}`);
		console.log(
			`Food scores: \n candy: ${foodScores.candy} \n tofu: ${foodScores.tofu} \n pizza: ${foodScores.pizza}`
		);
	}, [currentState, scoreTotal, foodScores]);

	const handleLeftClick = () => {
		console.log("Left button clicked - candy");
		setState(GAME_STATES.EATING);
		feedFood("candy");
		setTimeout(() => setState(GAME_STATES.IDLE), 1000);
	};
	const handleMiddleClick = () => {
		console.log("Middle button clicked - tofu");
		setState(GAME_STATES.EATING);
		feedFood("tofu");
		setTimeout(() => setState(GAME_STATES.IDLE), 1000);
	};
	const handleRightClick = () => {
		console.log("Right button clicked - pizza");
		setState(GAME_STATES.EATING);
		feedFood("pizza");
		setTimeout(() => setState(GAME_STATES.IDLE), 1000);
	};

	const handleCreatureClick = () => {
		console.log("Creature clicked!");
	};

	return (
		<group {...props} dispose={null} rotation={[0, 89.5, Math.PI]}>
			<group
				position={[0.03, -2.865, 0]}
				scale={[0.779, 2.767, 2.167]}
				ref={tamagotchiRef}
				onClick={handleCreatureClick}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere_2.geometry}
					material={materials["Material.003"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.214, 0]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
				ref={middleButtonRef}
				onClick={handleMiddleClick}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA001.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.332, 0.796]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
				ref={rightButtonRef}
				onClick={handleRightClick}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA002.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.332, -0.828]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
				ref={leftButtonRef}
				onClick={handleLeftClick}
			/>
		</group>
	);
}

useGLTF.preload("/tamagotchi.glb");
