/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Tamagotchi(props) {
	const { nodes, materials } = useGLTF("/tamagotchi.glb");
	return (
		<group {...props} dispose={null}>
			<group position={[0.03, -2.865, 0]} scale={[0.779, 2.767, 2.167]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Sphere_2.geometry}
					material={materials["Material.003"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.214, 0]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA001.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.332, 0.796]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.ButtonA002.geometry}
				material={materials["Material.004"]}
				position={[0.643, -1.332, -0.828]}
				rotation={[-1.572, -0.238, 1.583]}
				scale={[0.168, 0.106, 0.177]}
			/>
		</group>
	);
}

useGLTF.preload("/tamagotchi.glb");
